### ISSUE TITLE
max length

### ISSUE THREAD

**Issue by ZeroChaos-** [digininja/CeWL#105]
There is already a flag for min length `-m, --min_word_length: Minimum word length, default 3`
A matching max length flag would be great.  Probably not used much, but it might be nice.

**Comment by digininja** [comment]
Give this a try - https://github.com/digininja/CeWL/tree/max_length

```
	-x, --max_word_length: Maximum word length, default unset.
```

**Comment by ZeroChaos-** [comment]
tested and functional, thanks!

**Comment by ZeroChaos-** [comment]
https://github.com/digininja/CeWL/pull/106
