### ISSUE TITLE
Add redirection option

### ISSUE THREAD

**Issue by M4TxRx** [digininja/CeWL#108]
Is it possible to add a redirection option like -L option for Curl to follow redirection ?

**Comment by digininja** [comment]
Off the top of my head it already does, it just won't go off site unless
you've added that flag.

**Comment by M4TxRx** [comment]
What is this flag ?

**Comment by digininja** [comment]
If it is there it doesn't need a flag. I'm not at a machine to test it at
the moment.

**Comment by digininja** [comment]
I've just checked and it does already follow 301 and 302 redirects. No flag needed.
