### ISSUE TITLE
--meta_file flag not generating meta file

### ISSUE THREAD

**Issue by spacec0rgo** [digininja/CeWL#117]
Hi, I was writing a bash script that uses cewl as part of a bigger suite of tools.
I noticed that when passing the --meta_file flag, which I process to forward it to cewl, it doesn't generate the meta file.

I tried:
- `cewl -d 1 -m 5 -a -w ~/Desktop/cewlTest/domain.txt --meta_file ~/Desktop/cewlTest/meta_domain.txt --debug [URL]`
- `cewl -d 1 -m 5 -a --meta_file ~/Desktop/cewlTest/meta_domain.txt -w ~/Desktop/cewlTest/domain.txt --debug [URL]`
- `cewl -d 1 -m 5 -a --meta_file ~/Desktop/cewlTest/meta_domain.txt --debug [URL]` 

but none of them generate the file in the desired location (also tested with absolute paths).

Also tested with:
- `cewl -d 1 -m 5 -e --email_file ~/Desktop/cewlTest/email_domain.txt --debug [URL]`

since this flag seems to work in the same way, and it behaves correctly in both the command and inside the .sh script.
I can't really understand what's the problem here.

Screen attached.

![cewl_issue](https://github.com/digininja/CeWL/assets/149252773/390ecde4-7af1-4acd-8d1c-f67b8d62f259)

EDIT: contents of `/etc/os-release` for more information
```
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2024.2"
VERSION="2024.2"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
```

**Comment by digininja** [comment]
Fixed it in the latest push. It was a silly mistake that meant it only created the meta file if you'd specified you wanted email addresses rather than meta data.

Try again and it should work.

**Comment by digininja** [comment]
You'll need to pull from here as I don't know how long it will take Kali to catch up with my change.

**Comment by spacec0rgo** [comment]
Sorry for the delay, tested and everything is working fine.
We can close this issue, thank you for your support!

**Comment by digininja** [comment]
That's good, please close it now.
