### ISSUE TITLE
Unable to install Nokogiri gem

### ISSUE THREAD

**Issue by MetadataCleaner** [digininja/CeWL#125]
I get this error message when trying to install nokogiri:

Error: nokogiri gem not installed
    Run 'bundle install' to install all the required gems

~/CeWL $ gem install nokogiri
Fetching nokogiri-1.16.7.gem
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.7/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby extconf.rb
checking for whether -std=c99 is accepted as CFLAGS... yes
checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... yes
checking for whether -O2 is accepted as CFLAGS... yes
checking for whether -g is accepted as CFLAGS... yes
checking for whether -Winline is accepted as CFLAGS... yes
checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes
checking for whether -Wconversion -Wno-sign-conversion is accepted as CFLAGS... yes
Building nokogiri using packaged libraries.
Static linking is enabled.
Cross build is disabled.
Using mini_portile version 2.8.7
checking for iconv... yes
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libxml2-2.12.9.
Configuration options: --host\=aarch64-unknown-linux-android --enable-static --disable-shared --libdir\=/data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.7/ports/aarch64-linux-android/libxml2/2.12.9/lib --with-iconv\=yes --disable-dependency-tracking --without-python --without-readline --with-c14n --with-debug --with-threads --without-tls --disable-shared --enable-static CPPFLAGS\= CFLAGS\=-O2\ -U_FORTIFY_SOURCE\ -g\ -fPIC
The following patches are being applied:
  - 0001-Remove-script-macro-support.patch
  - 0002-Update-entities-to-remove-handling-of-ssi.patch
  - 0003-libxml2.la-is-in-top_builddir.patch
  - 0009-allow-wildcard-namespaces.patch
  - 0010-update-config.guess-and-config.sub-for-libxml2.patch
  - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch

The Nokogiri maintainers intend to provide timely security updates, but if
this is a concern for you and want to use your OS/distro system library
instead, then abort this installation process and install nokogiri as
instructed at:

  https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries

Note, however, that nokogiri cannot guarantee compatibility with every
version of libxml2 that may be provided by OS/package vendors.

Extracting libxml2-2.12.9.tar.xz into tmp/aarch64-unknown-linux-android/ports/libxml2/2.12.9... ERROR. Please review logs to see what happened:
----- contents of '/data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.7/ext/nokogiri/tmp/aarch64-unknown-linux-android/ports/libxml2/2.12.9/extract.log' -----
tar: libxml2-2.12.9/test/relaxng/ambig_name-class.xml: Cannot hard link to ‘libxml2-2.12.9/test/relaxng/ambig_name-class2.rng’: Permission denied
tar: libxml2-2.12.9/test/relaxng/ambig_name-class.rng: Cannot hard link to ‘libxml2-2.12.9/test/relaxng/tutorA.rng’: Permission denied
tar: Exiting with failure status due to previous errors
----- end of file -----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include=${opt-dir}/include
        --without-opt-include
        --with-opt-lib=${opt-dir}/lib
        --without-opt-lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --prevent-strip
        --enable-system-libraries
        --disable-system-libraries
        --use-system-libraries
        --enable-system-libraries
        --disable-system-libraries
        --use-system-libraries
        --enable-static
        --enable-cross-build
        --disable-cross-build
        --enable-cross-build
        --disable-cross-build
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include=${zlib-dir}/include
        --without-zlib-include
        --with-zlib-lib=${zlib-dir}/lib
        --without-zlib-lib
        --with-xml2-source-dir
/data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:623:in `block in execute': Failed to complete extract task (RuntimeError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:589:in `chdir'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:589:in `execute'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:575:in `extract_file'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:140:in `block in extract'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:138:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:138:in `extract'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/gems/mini_portile2-2.8.7/lib/mini_portile2/mini_portile.rb:233:in `cook'
        from extconf.rb:540:in `block (2 levels) in process_recipe'
        from extconf.rb:319:in `chdir'
        from extconf.rb:319:in `chdir_for_build'
        from extconf.rb:540:in `block in process_recipe'
        from <internal:kernel>:90:in `tap'
        from extconf.rb:438:in `process_recipe'
        from extconf.rb:871:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/extensions/aarch64-linux-android/3.3.0/nokogiri-1.16.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.7 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/3.3.0/extensions/aarch64-linux-android/3.3.0/nokogiri-1.16.7/gem_make.out

**Comment by digininja** [comment]
Did you read the logs it tells you to read?

Did you check why it was getting permission denied when trying to create
one of the files?

What have you done to try to fix the problem already?

**Comment by digininja** [comment]
I'll give support where people have tried to help themselves, but if you've done nothing then I'll leave you to it.
