### ISSUE TITLE
nothing saved if Ctrl+C is pressed while running

### ISSUE THREAD

**Issue by kbron** [digininja/CeWL#15]
It would be really nice if we could break a session and still getting the partial results saved

thank you

**Comment by digininja** [comment]
I should, have you tried it?

Robin

**Comment by kbron** [comment]
yes, I've tried. it just stops, but does not save anything.

**Comment by digininja** [comment]
Just checked the code and found this:

  89 # Doesn't work for some reason, maybe
  90 # because its bouncing into different classes

I knew the code was in there, it just doesn't work. I've just asked for
some help, will see what comes back.

**Comment by vdbaan** [comment]
I think I found a solution. The only thing that isn't responding to the break is the Net::HTTP::Get request. I've got it that, when that is finished all stops and the words are displayed.
Will send a pull request in a few.

**Comment by digininja** [comment]
I tried wrapping loads of functions in the break captures yesterday but
didn't find any that would work, I'll happily have a look at you PR.
