### ISSUE TITLE
Hey guys, there's a bug when processing offsite on a custom port

### ISSUE THREAD

**Issue by intrd** [digininja/CeWL#17]
![selection_739](https://cloud.githubusercontent.com/assets/2204686/25535306/f5e51bc4-2c0c-11e7-979f-ab7648e53e17.png)

..it falls back to port 80.

thx.

**Comment by digininja** [comment]
So you are starting on a custom port and when it tries to check another
site it reverts to port 80 and fails, is that the problem?

**Comment by intrd** [comment]
Same site..
I start from http://website.com:32914
But when it starts getting the internal urls like:

http://website.com:32914/hello-world
http://website.com:32914/hello-world2

it reverts to 80, but is the same site!

If I start cewl without -o flag, it does not even spider those urls..

By the way, solved the problem on iptables forwarding remotesite:32914 to localhost:80..

**Comment by digininja** [comment]
Are you using the latest from github? Thought I'd tested all this when I
added the last port checking

**Comment by digininja** [comment]
I've reproduced the problem, trying to work out what is causing it now.

**Comment by digininja** [comment]
Found it I think, try the port_checking branch and you'll need to set a depth which doesn't really make sense when going off site but for now it is needed.

**Comment by intrd** [comment]
Tested here!

`ruby cewl.rb http://mywebsite.com:33012/ --write port_test.txt --depth 1 -o -v`

The branch "port_checking" works perfect :)

thanks @digininja

**Comment by digininja** [comment]
OK, I'll get the branch merged into live, thanks for confirming the fix.
