### ISSUE TITLE
Doesnt find phone numbers

### ISSUE THREAD

**Issue by Apadgett879** [digininja/CeWL#18]
Hi, it seems that cewl will not pull the phone number (that also happens to be the password) off of the site that I am attempting to crawl. I am sure that I have it set at a large enough depth. It does pull a wordlist that it normally would though.

any suggestions?

(update to clarify issue)

**Comment by digininja** [comment]
It only looks for words, not number groups. If you wanted to match numbers as well you'd need to modify line 952:

```
words.gsub!(/[^[:alpha:]]/i, " ")
```

to include numbers as well.
