### ISSUE TITLE
Feature Request: Quitting saves partial wordlist (or allows option to restore previous session)

### ISSUE THREAD

**Issue by josephshanak** [digininja/CeWL#19]
It would be nice if when CeWL exit due to an interrupt it would stop spidering and finish writing the word list before it exited. For instance if I began spidering a very large site and I had the depth set pretty high, after an hour or two I might decide that it's probably collected enough words and hit Ctrl+C. Unfortunately when I do that, CeWL doesn't write anything to the output file and I have to start over with a lower depth.

Alternatively, maybe implementing some way to restore a previous run would be useful. 

As an alternative approach I tried using wget to mirror a site and then using various html2text utilities, awk, grep, etc to parse out words into a list offline, which works *ok* but is really dependent on the parsing, which CeWL already seems to do pretty well.

**Comment by digininja** [comment]
It was always supposed to but I could never get the ctrl-c handling to work. Try the latest code from master, it should all work now.

**Comment by josephshanak** [comment]
Yep, I just tried it on the latest code from master and it saved partial results when I hit ctrl+c. Closing request.
