### ISSUE TITLE
Invalid word - Get tag option

### ISSUE THREAD

**Issue by Themercee** [digininja/CeWL#2]
While using the tool on a website, I look at the wordlist produce by CeWL and I could see that there is a lot of invalids words. For exemple: function, class, x3d0, isStatic, getElementsByTagName, etc.

The website is a french website, so there is not supposed to be word in english and they are words from the html code. I don't code in ruby, so I can't help really much.

**Comment by digininja** [comment]
Unless the site is about JavaScript coding, it looks like some JavaScript
is being picked up by accident. Have you tried the newer branch, I improved
the filtering in there which may help.

As for picking up English words, there is nothing I can do about that, all
I do is to pick up things that are alpha strings that are separated by
certain characters.

**Comment by Themercee** [comment]
I will try the newer branch to see if it corrects the bugs. I suppose the certain characters are tag like p, div, span, etc?

**Comment by digininja** [comment]
the parser should remove all html formatting and just leave the text to be
processed, if that is failing then I'd need an example to look at to see
why. The JavaScript is slightly harder as I've tried to pull human text in
places but need to leave behind the JS code.

**Comment by Themercee** [comment]
I try the chaos version and the result is far better! Good job :+1:

**Comment by digininja** [comment]
Good to hear. I've not had enough feedback on it to risk pushing it to the
live version but will probably just do it anyway soon.

**Comment by g0tmi1k** [comment]
It's been merged now.
5.2 has been released!

**Comment by Themercee** [comment]
Nice, thanks guy keep the good work!
