### ISSUE TITLE
Removing common words?

### ISSUE THREAD

**Issue by ericblank** [digininja/CeWL#21]
Could there be a way to remove a list of common words from the generated list?

**Comment by digininja** [comment]
Not easily as trying to get people to agree on that list and then maintain
it would be a pain. I could easily do a tool that took two lists and
removed all the items in one from the other so you could keep your own
common word list.

**Comment by josephshanak** [comment]
> Could there be a way to remove a list of common words from the generated  list?

@ericblank, could you use rli or rli2 (or something else) from [hashcat-utils](https://hashcat.net/wiki/doku.php?id=hashcat_utils#rli) to remove common words?

This:

    $ touch in.txt remove.txt
    $ echo "a" >> in.txt
    $ echo "b" >> in.txt
    $ echo "c" >> in.txt
    $ echo "d" >> in.txt
    $ echo "e" >> in.txt
    $ echo "a" >> remove.txt
    $ echo "c" >> remove.txt
    $ rli in.txt out.txt remove.txt
    $ cat out.txt

Produces:

    b
    d
    e

**Comment by digininja** [comment]
Sounds like a perfect option.

**Comment by ericblank** [comment]
Thanks for all the tips! I knew the app existed but I couldn't find it.
