### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Os3r3um** [digininja/CeWL#23]
Hi, 

I'm getting this while trying to use the tool. Kali2017.2

CLI: ./cewl.rb -d 4 -m 5 -v -w custom_dict.txt <target>

```
The following error may help:
incorrect header check
/usr/lib/ruby/2.3.0/net/http/response.rb:380:in `inflate'
/usr/lib/ruby/2.3.0/net/http/response.rb:380:in `block in inflate_adapter'
/usr/lib/ruby/2.3.0/net/protocol.rb:411:in `call_block'
/usr/lib/ruby/2.3.0/net/protocol.rb:402:in `<<'
/usr/lib/ruby/2.3.0/net/protocol.rb:104:in `read'
/usr/lib/ruby/2.3.0/net/http/response.rb:402:in `read'
/usr/lib/ruby/2.3.0/net/http/response.rb:291:in `block in read_body_0'
/usr/lib/ruby/2.3.0/net/http/response.rb:262:in `inflater'
/usr/lib/ruby/2.3.0/net/http/response.rb:281:in `read_body_0'
/usr/lib/ruby/2.3.0/net/http/response.rb:202:in `read_body'
/usr/lib/ruby/2.3.0/net/http/response.rb:227:in `body'
/usr/lib/ruby/2.3.0/net/http/response.rb:164:in `reading_body'
/usr/lib/ruby/2.3.0/net/http.rb:1445:in `transport_request'
/usr/lib/ruby/2.3.0/net/http.rb:1407:in `request'
/usr/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
/usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
/usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
./cewl.rb:279:in `get_page'
./cewl.rb:209:in `block (2 levels) in start!'
./cewl.rb:207:in `each'
./cewl.rb:207:in `block in start!'
./cewl.rb:195:in `each'
./cewl.rb:195:in `start!'
./cewl.rb:161:in `start_at'
./cewl.rb:757:in `block in <main>'
./cewl.rb:747:in `catch'
./cewl.rb:747:in `<main>'

Caller
./cewl.rb:231:in `get_page'
./cewl.rb:209:in `block (2 levels) in start!'
./cewl.rb:207:in `each'
./cewl.rb:207:in `block in start!'
./cewl.rb:195:in `each'
./cewl.rb:195:in `start!'
./cewl.rb:161:in `start_at'
./cewl.rb:757:in `block in <main>'
./cewl.rb:747:in `catch'
./cewl.rb:747:in `<main>'

```

Any idea how I should fix it up?

Thank you.

**Comment by digininja** [comment]
Try the latest version from github, I don't know what version is in Kali
but it may not be completely up to date.

**Comment by Os3r3um** [comment]
Kali would be the latest version. updated today, 2 hours ago. 

The cewl version which I'm trying is CeWL 5.4 (Break Out), cloned from GitHub. 

Would be my ruby envy borked from whatever reasons and that's why I'm getting this error?

**Comment by Os3r3um** [comment]
That's cool. Will do it. Thank you!

**Comment by Os3r3um** [comment]
Right. So this is weird, the debug says: 

```
Starting at https://www.site/
Pushing {nil=>"https://www.site/"}
Checking page https://www.site/
Comparing https://www.site/ with https://www.site/

Unable to connect to the site (https://www.site:443/)
```

Browsing the site goes flawlessly though.

**Comment by digininja** [comment]
The error is coming from line 380 of /usr/lib/ruby/2.3.0/net/http/response.rb:

```
379       block = proc do |compressed_chunk|
380         @inflate.inflate(compressed_chunk) do |chunk|
381           dest << chunk
382         end
383       end
```

This is code that inflates compressed code so it suggests that the compressed header being sent by the site is corrupt in some way. I've added an extra error handler for what I think is the error being thrown, can you pull the code from the headerror branch and see if works. I can't reproduce your error so haven't tested it but it might work.

**Comment by Os3r3um** [comment]
Yeah. All good now. A big thank you!

**Comment by digininja** [comment]
I'll tidy up the error message and merge that code in. Thanks for reporting
it.

**Comment by Os3r3um** [comment]
That's really sweet. Probably people will expect to see this reflected quite soon with the Kali updates. have no idea how the whole Kali packaging process does actually work. 

Anyway, once again a big thank you for your time invested into this. :)

**Comment by digininja** [comment]
The fix has just been merged into the master branch.
