### ISSUE TITLE
Not all websites return a set?

### ISSUE THREAD

**Issue by fallenreaper** [digininja/CeWL#25]
I was a bit confused by this.   It seems that some websites are immune to using cewl.

while doing google works:  `cewl www.google.com -m 6 -w outfile.txt` but then when I tried some other sites, it was giving me no results.  Example:  `cewl www.spiderlabs.com -m 6 -w outfile.txt`, I also noticed it has the same affect for `sega.com` and `bentley.com`

Did they developed rules to counteract the spidering, or am I doing something wrong?

**Comment by digininja** [comment]
Run it in verbose mode and see what it says.

**Comment by fallenreaper** [comment]
It says "Offsite link, not following". Interesting.  It seems that spiderlabs points to trustwave points to https://www.trustwave.com points to https:/home .  ?

**Comment by fallenreaper** [comment]
Domain hopping is throwing a "offsite link, not following" soft error.  To circumvent this on websites, just check against `cewl URL --offsite -v -m 6 -w outputFile.txt`

**Comment by digininja** [comment]
That's why it's not scanning it then, it doesn't go off the hostname you've
provided without permission. You'll need to manually navigate to the final
hostname and then scan that.
