### ISSUE TITLE
NEED HELP 

### ISSUE THREAD

**Issue by wermaxta** [digininja/CeWL#27]
My OS  is Kali Linux  
Linux kali 4.13.0-kali1-amd64 #1 SMP Debian 4.13.13-1kali1 (2017-11-17) x86_64 GNU/Linux
ruby -v ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
when i type 
./cewl.rb i got this 
CeWL 5.4 (Break Out) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ./cewl_lib (LoadError)
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /pentest/password-recovery/CeWL/cewl.rb:89:in `<main>'

thank you

**Comment by digininja** [comment]
How did you install it?

**Comment by wermaxta** [comment]
git clone https://github.com/digininja/CeWL.git
and i install all gem from Gemfile

**Comment by wermaxta** [comment]
i fix it :)
Thank you
