### ISSUE TITLE
using -d 0, I get no entries

### ISSUE THREAD

**Issue by stahnirockt** [digininja/CeWL#32]
When using the preinstalled cewl (version 5.3) on Kali, I can use -d 0 to get only results from the webpage I want. Cloning and using version 5.4.2 from GitHub I didn't get entries with -d 0, only with -d 1 but then I haven't the results of the wanted page only the "subpages".

**Comment by digininja** [comment]
Are you saying 5.4.2 isn't getting words off the front page?

**Comment by stahnirockt** [comment]
Yes, that's what I wanted to say. I've tried a bit more and the problem does not occur on all websites.
For example, https://github.com gives the same result in both versions. But https://en.wikipedia.org/wiki/Computer does not provide frontpage results in version 5.4.2, but it does in version 5.3. Same result with every wikipedia entry. Any idea, what could be the problem. I was trying this on mac and linux, same results.

**Comment by digininja** [comment]
I've not got a Kali box to try it on but I'll make sure that the depth
feature works as expected on the Github master.

Will probably be the next couple of days before I can look at it though. If
I don't get back to you by the end of the week give me a nudge.

**Comment by stahnirockt** [comment]
Today, I've tried a little further. If I create a website with a link to a wikipedia entry and append '-d 1' and '-o', I get the results of the wanted page. 

Also, it seems that commenting out line 706 solved the problem for me.
```
# The spider doesn't work properly if there isn't a / on the end
if url !~ /\/$/
#	url = "#{url}/"
end
```
It was also commented out in version 5.3.

**Comment by digininja** [comment]
That change went in because there was another issue raised that it was
stopping spidering working with it there. I'll have to do some proper
digging, my guess is it has something to do with sites that do automatic
redirection from URLs without trailing slashes to with a slash.

**Comment by digininja** [comment]
Assume it is all working now, not had any recent complaints.
