### ISSUE TITLE
grabbing possible passwords with numbers

### ISSUE THREAD

**Issue by roperope** [digininja/CeWL#35]
hi,
i tried to grab some words from a site, but the words that contain numbers (p4ssw0rds,g0tmi1k ...)don't end up in my word list .
i am using cewl 5.3 
command i am using: cewl http://192.168.1.10/personal -d 2 -m 6 -w /Desktop/wordlist.txt -v

is it possible to get these words also in my grabbed word list?

thx 
rope

**Comment by digininja** [comment]
Give this branch a try and see if it does what you want

https://github.com/digininja/CeWL/tree/withnumb

**Comment by roperope** [comment]
hi digininja,
thx for the fast reply
how do use this branch? do i just replace the new gemfile, gemfile.lock, cewl.rb, cewl_lib.rb, fab.rb from this branch with the old ones or do i need to reinstall the whole program to make it work?
i am using kali-linux and i am fairly new at this
grtz
rope

**Comment by digininja** [comment]
If you don't know git, the easiest way is probably to go to the repo,
change to the branch in the drop down on the left hand side then download
the source using a link on the right.

Or something like

git clone <repo>
cd CeWL
git checkout withnumb

I'm not on a machine at the moment to check those commands.

**Comment by roperope** [comment]
hi,

it worked with the "withnumb" brance
but now i have 2 versions of cewl on my kali system
is there a way i can change the pre-installed version in kali to work with de numb brance version?

greetz
rope

**Comment by digininja** [comment]
You could just copy the files you checked out over the ones from the distro
but then if you do an update the changes will be lost.

I'll see about making this a feature with an extra command line parameter
then make it a full release which Kali may pick up on.

**Comment by digininja** [comment]
Looks like we both did something wrong, I checked the updates into the master branch instead of withnum and you pulled from the wrong branch, got master and got the changes.

Odd pairing of mistakes.
