### ISSUE TITLE
Fixnum issue

### ISSUE THREAD

**Issue by brainst0rm** [digininja/CeWL#36]
Hi, I am trying to use Cewl on Kali Linux and I run into following error when I try to make a list.

CeWL 5.3 (Heading Upwards) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
/usr/lib/ruby/vendor_ruby/spider/spider_instance.rb:125: warning: constant ::Fixnum is deprecated

Any clues please?

**Comment by digininja** [comment]
One of the gems it relies on is very old and creeky and slowly falling to
pieces. I've fixed the issue in the latest GitHub code so if you want to
remove the error just use that instead.

**Comment by digininja** [comment]
You should be able to do a checkout from GitHub to get the latest version.

**Comment by digininja** [comment]
Closing if I don't hear back.
