### ISSUE TITLE
Fixnum is depricated

### ISSUE THREAD

**Issue by CXVVMVII** [digininja/CeWL#39]
hi ,
i've problem when i use Cewl when i run it show me this "/usr/lib/ruby/vendor_ruby/spider/spider_instance.rb:125: warning: constant ::Fixnum is deprecated"
please can u tell me what should i do

**Comment by digininja** [comment]
This was fixed with this commit back in April:

https://github.com/digininja/CeWL/commit/d86e3250c0fd27c2e740cf9281b7c68cec1e40e3#diff-e9785f85b3c4bec98fdad1f8f609c3a3

If you run the latest version it should be fine

**Comment by adem313** [comment]
thanx digininja it's been fixed ;)
