### ISSUE TITLE
Issue with CeWL "grinding"?

### ISSUE THREAD

**Issue by braimee** [digininja/CeWL#40]
Hi there,

I'm running the latest CeWL on a fresh Kali VM, and asked it to do a pretty light enumeration of a site (depth of 1 and minimum character count of 7).  CeWL will just grind away for hours and never finish (and never write anything to the output .txt file).  It also seems to drag down performance of the VM and make it unresponsive (even though *top* doesn't seem to indicate the ruby is crushing the VM).  CeWL is the only thing running on the VM.

Curious if you've ever seen this before or have any troubleshooting ideas to try?

Thanks,
Brian

**Comment by digininja** [comment]
Not something I've noticed before, can you share the URL?

**Comment by braimee** [comment]
No, but let me try from another Kali machine next week and see if it's "just a me thing."  Thanks.

**Comment by digininja** [comment]
Try running the latest GitHub version as that is the easiest for me to
debug is there is a problem.

**Comment by braimee** [comment]
Hi, I turned on verbose logging and found that CeWL seemed to stop crawling the site about 20 minutes into operation.  However, upon subsequent runs it gets stuck again - but in a different place.  I have a feeling something on the client side is stepping in and throttling/blocking requests.  So I'm pretty sure it's a site-specific issue, thus I'm closing this thread.  Thanks.
