### ISSUE TITLE
Lithuanian characters disappear in output

### ISSUE THREAD

**Issue by shinshilas** [digininja/CeWL#46]
When scanning a page the output comes with no lithuanian characters such as ĄČĘĖĮŠŲŪŽ, they just disappear. For example when scanning www.google.lt:
paie
Paie
lapiai
Nar
ymo
rankiai
lygos

Which I THINK should be:
paieŠka
PaieŠka
Šlapiai
Nar    #this one seems to be seperated in two words with the one below because of unrecognized character
ymo
Įrankiai
sĄlygos

Tested with newest 5.4.3 version, tried one from Kali repo and from github.

**Comment by digininja** [comment]
I just ran it against that domain and got this, it is definitely picking up some non-ascii characters. As Google can be a moving target, can you give a more static example of a site where it fails?

![image](https://user-images.githubusercontent.com/117081/50210970-61e28880-036f-11e9-9a6f-012384da4029.png)

**Comment by digininja** [comment]
#43 was merged on the 20th September so is in the master branch. As long as you use the latest from there you'll have the working version.

**Comment by shinshilas** [comment]
Thats because of my stupidity, I downloaded from releases tab. Thanks for your help :)

**Comment by digininja** [comment]
I've just done a new release based on the current master so shouldn't trip
anyone else up.
