### ISSUE TITLE
Program doesn't collect anything 

### ISSUE THREAD

**Issue by mrkoww** [digininja/CeWL#51]
root@kali:~# cewl -w customwordlist.txt -v -d 1 -m 5 www.amigos.com
CeWL 5.4.4.1 (Arkanoid) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
Starting at http://www.amigos.com
Offsite link, not following: https://www.amigos.com/
Writing words to file
root@kali:~# cewl -w customwordlist.txt -v -d 1 -m 5 www.gothub.com
CeWL 5.4.4.1 (Arkanoid) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
Starting at http://www.gothub.com
Offsite link, not following: http://eepurl.com/ddJb_z
Writing words to file
root@kali:~# cewl -w customwordlist.txt -v -d 1 -m 5 www.github.com
CeWL 5.4.4.1 (Arkanoid) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
Starting at http://www.github.com
Offsite link, not following: https://www.github.com/
Writing words to file
root@kali:~# cewl -w customwordlist.txt -d 5 -m 7 www.hak5.com
CeWL 5.4.4.1 (Arkanoid) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
root@kali:~# cewl -w customwordlist.txt -v -d 1 -m 5 www.github.com
CeWL 5.4.4.1 (Arkanoid) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
Starting at http://www.github.com
Offsite link, not following: https://www.github.com/
Writing words to file
root@kali:~# cewl -w customwordlist.txt -d 5 -m 7 www.hak5.com
CeWL 5.4.4.1 (Arkanoid) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
root@kali:~# ^C
root@kali:~# cewl -w customwordlist.txt -d 2 www.hak5.com
CeWL 5.4.4.1 (Arkanoid) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
root@kali:~# cewl -w customwordlist.txt -d 2 www.hak5.com -v
CeWL 5.4.4.1 (Arkanoid) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
Starting at http://www.hak5.com
Offsite link, not following: http://ww7.hak5.com
Writing words to file
root@kali:~# cewl -w customwordlist.txt -d 2 www.cnn.com -v
CeWL 5.4.4.1 (Arkanoid) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
Starting at http://www.cnn.com
Offsite link, not following: https://www.cnn.com/
Writing words to file
root@kali:~# cewl -d 2 http://www.cnn.com/
CeWL 5.4.4.1 (Arkanoid) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
root@kali:~# cewl -d 2 http://www.cnn.com/ -v
CeWL 5.4.4.1 (Arkanoid) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
Starting at http://www.cnn.com/
Offsite link, not following: https://www.cnn.com/
Words found

**Comment by digininja** [comment]
Your version is at least two releases out of date so please always use the
latest version when reporting issues.

If you read the error messages, in most instances it looks like the URLs
you've given are redirecting from http to https which is considered a
different site so won't be processed.

**Comment by mrkoww** [comment]
The program advises it is up to date

**Comment by mrkoww** [comment]
Maybe I am high as a cloud but my version is 5.4.4 the latest update on this iste is 5.4.3, I also attempted to download any updates and it advises "cewl is already the newest version".

**Comment by mrkoww** [comment]
Maybe I am mistaken but my version is 5.4.4 the latest update on this iste is 5.4.3, I also attempted to download any updates and it advises "cewl is already the newest version".

**Comment by digininja** [comment]
The latest version, from Githib is the only version I support. Currently at
VERSION = "5.4.6 (Exclusion)"
I don't support any packaged versions regardless of the distribution.

But, even if you get to the latest version, your problem is the same, you
are specifying HTTP addresses, getting a redirect to HTTPS which is
considered off site so CeWL refuses to scan it.

**Comment by mrkoww** [comment]
I downloaded the latest version from here (GitHub) and it still says 5.4.4.1, your webpage says 5.4.2 is the latest and this github notes say 5.4.3,🤷 maybe we're operating in parallel universes. 

Regardless I have tried both HTTP and HTTPS and neither works. I've tried about 100 different sites and none work. Just going to count this as a lost cause and whip up a similar in VSC++ 🤷

**Comment by mrkoww** [comment]
Found and compiled latest version, only works in verbose mode and doesn't save to file so far. 

~/CeWL# ./cewl.rb -w customwordlist.txt -d 5 -m 7 -v https://www.cnn.com
CeWL 5.4.6 (Exclusion) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
Starting at https://www.cnn.com
Visiting: https://www.cnn.com, got response code 200
Attribute text found:
visit the US section visit the W (insert 6000 words here)
Writing words to file . . .

**Comment by digininja** [comment]
By found and compiled, do you mean you did a git clone of this repo and then ran the script? It is interpreted, not compiled.

It should work fine in normal and verbose modes, you just won't see any output until it is finished if you don't have verbose enabled.

**Comment by squid22** [comment]
is there a way to ignore the server response? let's say the server sends 403 forbidden...but still shows a site...
