### ISSUE TITLE
Not working for javascript rendered HTML pages

### ISSUE THREAD

**Issue by anandumdas** [digininja/CeWL#53]
The target app uses react js and the html pages are dynamically generated from the front end. CeWl fails to collect words in this case. Any solutions?

**Comment by digininja** [comment]
It won't work as it does no JavaScript execution.

The only idea I've got for stuff like that is to browse the site through
burp then save out the rendered pages and process those. You could either
do it on the command line or get it all in one file and through it on a web
server and point CeWL at the one page.

**Comment by anandumdas** [comment]
Thanks for the quick response. 

And probably, you can consider it as a new feature, by making use of something like [this](https://stackoverflow.com/a/28210058/4202092)?

Feel free to close the issue as well.

**Comment by digininja** [comment]
I'll have a look through it and see.

**Comment by sebaspf** [comment]
I solved it using [https://www.brow.sh/ ](https://www.brow.sh/). Browsh is a text-based browser that renders the websites (html, css, js, images, etc. ) using an headless Firefox. You can start is in server mode and request a plain text version of the site.

```sh
# start the server
browsh --http-server-mode

# Open a new terminal
# Request the site in plain text using a header
 cewl --header "X-Browsh-Raw-Mode: PLAIN" localhost:4333/https://google.com
```

**Comment by digininja** [comment]
@sebaspf Nice idea. Fancy submitting a PR to the README file on how to get this working? Would need to be really simple and go from install to fully running.
