### ISSUE TITLE
Install cewl at ubuntu 14.04 Help

### ISSUE THREAD

**Issue by stereonov** [digininja/CeWL#58]
Hello trying to install cewl 'https://github.com/digininja/CeWL/releases/tag/5.2' at ubuntu 14.04 but not working.
I have follow all instructions from here: https://digi.ninja/projects/cewl.php
Some dependencies was require ruby version 2.0 and others version 2.5 however i have install a few versions and all dependencies have installed.
'bundle install' has success.
Also make directory executable but when I navigate to directory and execute:
cewl --help
I get:
`No command 'cewl' found, did you mean:
 Command 'mewl' from package 'mew-beta-bin' (universe)
 Command 'mewl' from package 'mew-bin' (universe)
cewl: command not found`

Can you please tell me what I am doing wrong?
Thank you very much!

**Comment by digininja** [comment]
Linux doesn't automatically have the current directory in the path and so
you have to specify where you are loading the app from:

```
./cewl.rb <params>
```

**Comment by stereonov** [comment]
Can't believe it was so easy... Thank you so much, great work!
