### ISSUE TITLE
Progress Indication

### ISSUE THREAD

**Issue by zedseven** [digininja/CeWL#71]
Pointing this tool at bigger sites/wikis can take quite a long time, and it can be difficult to be sure it's actually doing something until it finishes or I force-kill it.

It would be very useful to have some kind of progress indication, whether that would be something simple like displaying the current page being processed, a count of words found, etc. This would make it much easier to be sure it's working and to gauge how far along it is.

Perhaps this issue is moreso about it being slow with the way I'm running it, but pointing it at something like a wikipedia article with default depth took over a day and I ended up killing it. (I later realized a depth of 2 was likely too high, but the point remains)

**Comment by digininja** [comment]
I can't do a progress bar as I've no idea how big the site is before I
start the spider.

You can dump out all the page information already with the `-v` flag.

**Comment by zedseven** [comment]
I know, that's why all my suggestions were things that did not rely on knowing a total number (count of words found, current page, etc). My point was that it was difficult to be sure it was doing anything, as there was no visual indication.

I guess `-v` will work for now.
