### ISSUE TITLE
Unable to connect to the site 

### ISSUE THREAD

**Issue by palyweb** [digininja/CeWL#72]
Hello Robin Wood :) 
Unfortunately I can't CeWL my site:  :(
Do you have any ideas?

---------------------------
cewl http://a-wareness.fr --debug -v
CeWL 5.4.8 (Inclusion) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
Starting at http://a-wareness.fr
Pushing {nil=>"http://a-wareness.fr"}
Checking page http://a-wareness.fr
Comparing http://a-wareness.fr with http://a-wareness.fr

Unable to connect to the site (http://a-wareness.fr:80/)

The following error may help:
execution expired
/usr/lib/ruby/2.7.0/net/http.rb:960:in `initialize'
/usr/lib/ruby/2.7.0/net/http.rb:960:in `open'
/usr/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
/usr/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
/usr/lib/ruby/2.7.0/net/http.rb:958:in `connect'
/usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
/usr/lib/ruby/2.7.0/net/http.rb:932:in `start'
/usr/lib/ruby/2.7.0/net/http.rb:1483:in `request'
/usr/bin/cewl:246:in `get_page'
/usr/bin/cewl:176:in `block (2 levels) in start!'
/usr/bin/cewl:174:in `each'
/usr/bin/cewl:174:in `block in start!'
/usr/bin/cewl:162:in `each'
/usr/bin/cewl:162:in `start!'
/usr/bin/cewl:114:in `start_at'
/usr/bin/cewl:769:in `block in <main>'
/usr/bin/cewl:759:in `catch'
/usr/bin/cewl:759:in `<main>'

Caller
/usr/bin/cewl:198:in `get_page'
/usr/bin/cewl:176:in `block (2 levels) in start!'
/usr/bin/cewl:174:in `each'
/usr/bin/cewl:174:in `block in start!'
/usr/bin/cewl:162:in `each'
/usr/bin/cewl:162:in `start!'
/usr/bin/cewl:114:in `start_at'
/usr/bin/cewl:769:in `block in <main>'
/usr/bin/cewl:759:in `catch'
/usr/bin/cewl:759:in `<main>'

End of main loop
Words found
End of wordlist loop
End of email loop
End of meta loop

----------------

**Comment by digininja** [comment]
Looks like I'm not catching the timeout exception from
http://a-wareness.fr:80/ which shouldn't be timing out.

I'll give it a test later.

**Comment by digininja** [comment]
You aren't going to like this, it works fine for me.

The fact you are calling it from the path rather than from the current directory I'm guessing you are running a version that has been installed by a package manager. Give it a try with the latest from GitHub and see if that works.

**Comment by palyweb** [comment]
Thank you for your feedback :)
Yet CeWL works on other sites 
But problem still same from the last GitHub version :

./cewl.rb http://a-wareness.fr --debug -v
CeWL 5.5.0 (Grouping) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
Starting at http://a-wareness.fr
Pushing {nil=>"http://a-wareness.fr"}
Checking page http://a-wareness.fr
Comparing http://a-wareness.fr with http://a-wareness.fr

Unable to connect to the site (http://a-wareness.fr:80/)

The following error may help:
execution expired
/usr/lib/ruby/2.7.0/net/http.rb:960:in `initialize'
/usr/lib/ruby/2.7.0/net/http.rb:960:in `open'
/usr/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
/usr/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
/usr/lib/ruby/2.7.0/net/http.rb:958:in `connect'
/usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
/usr/lib/ruby/2.7.0/net/http.rb:932:in `start'
/usr/lib/ruby/2.7.0/net/http.rb:1483:in `request'
./cewl.rb:247:in `get_page'
./cewl.rb:177:in `block (2 levels) in start!'
./cewl.rb:175:in `each'
./cewl.rb:175:in `block in start!'
./cewl.rb:163:in `each'
./cewl.rb:163:in `start!'
./cewl.rb:115:in `start_at'
./cewl.rb:776:in `block in <main>'
./cewl.rb:766:in `catch'
./cewl.rb:766:in `<main>'

Caller
./cewl.rb:199:in `get_page'
./cewl.rb:177:in `block (2 levels) in start!'
./cewl.rb:175:in `each'
./cewl.rb:175:in `block in start!'
./cewl.rb:163:in `each'
./cewl.rb:163:in `start!'
./cewl.rb:115:in `start_at'
./cewl.rb:776:in `block in <main>'
./cewl.rb:766:in `catch'
./cewl.rb:766:in `<main>'


End of main loop
Words found
End of wordlist loop
End of email loop
End of meta loop

**Comment by digininja** [comment]
Weird.

Can you get to the site with curl? With the port number on it.

**Comment by palyweb** [comment]
Yes curl works ... :/

**Comment by digininja** [comment]
Is it slow to respond? If you can connect but CeWL gets a timeout it could
be because it is slow to respond and CeWL times out before curl does.

**Comment by palyweb** [comment]
Nop, very fast !!!
Grrr, I don't understand.
I'll try with another connection ;)

**Comment by digininja** [comment]
Do you have a proxy set up?

**Comment by palyweb** [comment]
No

**Comment by digininja** [comment]
How's your ruby? I'll have a look at it tomorrow and send you some extra
debug to add. We will get to the bottom of it.

If you could try it on another machine before that though, it would help
rule out if it is that machine/install or if it is more widespread.

**Comment by palyweb** [comment]
ok after many tests, the problem comes from my IP address. 
It works on other sites but not on this one.

Thank you for your time ^^

**Comment by digininja** [comment]
Anything odd in your hosts file?

It could be a dependency issue with the pre-installed gems.

I don't like issues like this as they always mean something is wrong
somewhere and I don't like not knowing! If you do manage to get any more
clues to what it is, let me know.
