### ISSUE TITLE
Gemfile and README.md conflict

### ISSUE THREAD

**Issue by ZeroChaos-** [digininja/CeWL#73]
README.md says "mime-types" and "rubyzip" are required, but the Gemfile actually calls for "zip" and "mime" which are different gems.

Afaik, the ones specified in README.md are the "preferred" gems to use.  Can you please correct Gemfile, Gemfile.lock, and confirm the code actually uses the right gems?  At least the zip gem seems to be called directly, I can't tell for mime because I know less about it.

**Comment by digininja** [comment]
I'll have a look at and see.

Can't say off the top of my head as I've no idea which is which.

**Comment by blshkv** [comment]
It's sad to see a new release without this fix. Ping?

**Comment by digininja** [comment]
Feel free to submit a PR, if not, I'll try to get to it soon.

**Comment by digininja** [comment]
The only mistake in the README was rubyzip which should have been zip, I've fixed that.
