### ISSUE TITLE
please switch from zip to rubyzip

### ISSUE THREAD

**Issue by ZeroChaos-** [digininja/CeWL#79]
the ruby gem "zip" was last updated in 2010 while "rubyzip" was updated in 2020.

My real motive, zip isn't packaged in gentoo and I don't want to add an unmaintained gem.

**Comment by digininja** [comment]
Done that for you. Accidentally did it on Master branch so hope it works, seems to for me.

Give it a go.

**Comment by ZeroChaos-** [comment]
seems to work okay, afaict

**Comment by digininja** [comment]
Woo!
