### ISSUE TITLE
[Feature Request] add range to groups of words

### ISSUE THREAD

**Issue by Shooter3k** [digininja/CeWL#83]
Would it be possible to add a range to groups of words? 

example: 

cewl.rb -g 2-5 
or
cewl.rb -g 2 -g 3 -g 4 -g 5
or
cewl.rb -g 2,3,4,5

**Comment by digininja** [comment]
Check out the grouping branch, you can now specify the group lengths with a comma separated list:

```
./cewl.rb -g 2,6 cewl.test
```

**Comment by digininja** [comment]
Is this as you expected? Can this be closed?

**Comment by Shooter3k** [comment]
I haven't had  chance but I'm betting it works awesome. Thanks, you can close it

**Comment by Shooter3k** [comment]
this works amazingly! Thanks for doing this
