### ISSUE TITLE
question about releases

### ISSUE THREAD

**Issue by 06kellyjac** [digininja/CeWL#90]
It looks like `5.4.3.2` is newer than `5.5.2` ... is that correct?

Also are there any plans to make a new release soon with some of the dependency updates? :slightly_smiling_face:

**Comment by digininja** [comment]
Just take the latest from the main/master branch, that is the current
version and the only one I support.

I always forget to do releases and tend only to do them when a distro asks
me to do they can update a package.

**Comment by 06kellyjac** [comment]
I was actually checking in terms of packaging for a distro 😅 - nixos/nixpkgs, but its fine, we can grab commits off master and tag `unstable-yyyy-mm-dd`

**Comment by digininja** [comment]
That's good.

If you ever need a release tagging, just let me know. I don't mind doing
it, I just never remember.
