### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by alainlankers** [digininja/CeWL#95]
I followed the install instruction but get an error when running (system is Debian 11):

./cewl.rb http://www.xxxxxx.com/
CeWL 5.5.2 (Grouping) Robin Wood (robin@digi.ninja) (https://digi.ninja/)
Traceback (most recent call last):
	11: from ./cewl.rb:27:in `<main>'
	10: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	 9: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	 8: from /usr/lib/ruby/vendor_ruby/nokogiri.rb:36:in `<top (required)>'
	 7: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:96:in `require'
	 6: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:96:in `require'
	 5: from /var/lib/gems/2.7.0/gems/nokogiri-1.13.6-x86_64-linux/lib/nokogiri/xml.rb:53:in `<top (required)>'
	 4: from /var/lib/gems/2.7.0/gems/nokogiri-1.13.6-x86_64-linux/lib/nokogiri/xml.rb:53:in `require_relative'
	 3: from /var/lib/gems/2.7.0/gems/nokogiri-1.13.6-x86_64-linux/lib/nokogiri/xml/node.rb:6:in `<top (required)>'
	 2: from /var/lib/gems/2.7.0/gems/nokogiri-1.13.6-x86_64-linux/lib/nokogiri/xml/node.rb:7:in `<module:Nokogiri>'
	 1: from /var/lib/gems/2.7.0/gems/nokogiri-1.13.6-x86_64-linux/lib/nokogiri/xml/node.rb:56:in `<module:XML>'
/var/lib/gems/2.7.0/gems/nokogiri-1.13.6-x86_64-linux/lib/nokogiri/xml/node.rb:59:in `<class:Node>': uninitialized constant Nokogiri::ClassResolver (NameError)

**Comment by digininja** [comment]
What is the output from `gem list`?

**Comment by alainlankers** [comment]
gem list

*** LOCAL GEMS ***

activesupport (6.1.6)
addressable (2.8.0, 2.7.0)
benchmark (default: 0.1.0)
bigdecimal (default: 2.0.0)
bundler (2.3.17, default: 2.1.4)
cgi (default: 0.1.0)
cms_scanner (0.13.8)
concurrent-ruby (1.1.10)
csv (default: 3.1.2)
date (default: 3.0.0)
dbm (default: 1.1.0)
delegate (default: 0.1.0)
did_you_mean (default: 1.4.0)
etc (default: 1.1.0)
ethon (0.15.0)
fcntl (default: 1.0.0)
ffi (1.15.5)
fiddle (default: 1.0.0)
fileutils (default: 1.4.1)
forwardable (default: 1.3.1)
gdbm (default: 2.1.0)
get_process_mem (0.2.7)
getoptlong (default: 0.1.0)
i18n (1.10.0)
io-console (default: 0.5.6)
ipaddr (default: 1.2.2)
ipaddress (0.8.3)
irb (default: 1.2.6)
json (default: 2.3.0)
logger (default: 1.4.2)
matrix (default: 0.2.0)
mime (0.4.4)
mime-types (3.4.1, 3.3.1)
mime-types-data (3.2022.0105, 3.2015.1120)
mini_exiftool (2.10.2, 2.9.0)
minitest (5.13.0)
mutex_m (default: 0.1.0)
net-http-digest_auth (1.4)
net-pop (default: 0.1.0)
net-smtp (default: 0.1.0)
net-telnet (0.1.1)
nokogiri (1.13.6 x86_64-linux, 1.11.1)
observer (default: 0.1.0)
open3 (default: 0.1.0)
openssl (default: 2.1.2)
opt_parse_validator (1.9.5)
ostruct (default: 0.2.0)
pkg-config (1.4.4)
power_assert (1.1.7)
prime (default: 0.1.1)
pstore (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (4.0.7, 3.0.3)
racc (1.6.0, default: 1.4.16)
rake (13.0.3)
rchardet (1.8.0)
rdoc (default: 6.2.1.1)
readline (default: 0.0.2)
readline-ext (default: 0.1.0)
reline (default: 0.1.5)
rexml (3.2.5, default: 3.2.3.1)
rss (default: 0.2.8)
ruby-progressbar (1.11.0)
rubygems-update (3.2.5)
rubyzip (2.3.2, 2.0.0)
sdbm (default: 1.0.0)
singleton (default: 0.1.0)
spider (0.42, 0.5.4)
stringio (default: 0.1.0)
strscan (default: 1.0.3)
sys-proctable (1.2.6)
test-unit (3.3.9)
timeout (default: 0.1.0)
tracer (default: 0.1.0)
typhoeus (1.4.0)
tzinfo (2.0.4)
uri (default: 0.10.0)
webrick (default: 1.6.1)
wpscan (3.8.22)
xmlrpc (0.3.0)
yajl-ruby (1.4.3)
yaml (default: 0.1.0)
zeitwerk (2.5.4)
zlib (default: 1.1.0)

**Comment by alainlankers** [comment]
Not sure what was exactly the issue but its working fine now.
