### ISSUE TITLE
--exclude not working

### ISSUE THREAD

**Issue by Pusher91** [digininja/CeWL#97]
I am running this command:
`cewl http://faculty.htb/admin/ -H 'Cookie: PHPSESSID=i8srqte0pgvltdlnffi69769t6' -d 6 --exclude cewl.exclude --debug`

cewl.exclude contains a single line:
`ajax.php?action=logout`

When I run the cewl command with --debug it detects the following links
`links = ["#", "ajax.php?action=logout", "index.php?page=home", "index.php?page=courses", "index.php?page=subjects", "index.php?page=faculty", "index.php?page=schedule", "#"]`

However, I also find in the debug output that is still checks the url that I have listed in my exclude file:
`Checking page http://faculty.htb:80/admin/ajax.php?action=logout`

After it checks the logout url (/ajax.php?action=logout), I lose my cookie and the script dies shortly after.

Am I doing something wrong?  I have tried including other urls in my exclude file as well, such as:

- http://faculty.htb/admin/ajax.php?action=logout
- faculty.htb/admin/ajax.php?action=logout
- /admin/ajax.php?action=logout
- /ajax.php?action=logout

It still hits the logout url and kills my cookie, which ends the word scraping.

**Comment by digininja** [comment]
Assuming this fixed it.
